base/api/urls.py
from django.urls import path
from . import views



urlpatterns =[
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
   
    path('rooms/member/<str:pk>/', views.getParticipants),
    


]

base/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),

    # Password reset views
    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='base/reset_password.html'), name='reset-password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='base/reset_password_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='base/reset_password_confirm.html'), name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='base/reset_password_complete.html'), name='password_reset_complete'),
    path('profile/password/update', views.updatePassword, name="update-password"),
    path('profile/password/change', views.changePassword, name="change-password"),
    # forgot password finished

   # user preference
   path('preference/',views.user_preference, name="preference"),
   path('preference/user',views.user_preference_edit, name="user_preference"),
   path('preference/add/',views.add_preference, name="add_preference"),
   path('preference/edit/',views.edit_preference, name="edit_preference"),

    path('', views.index),
    path('home/', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    path('update-user/', views.updateUser, name="update-user"),
    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activities"),
    path('join/<str:pk>', views.joinRoom, name="join-room"),
    path('leave/<str:pk>', views.leaveRoom, name="leave-room"),
    path('user/remove', views.removeUser, name="remove-user"),
    path('open_file/<int:file_id>/', views.open_file, name='open-file'),
    path('download_image/<int:image_id>/',
         views.download_image, name='download-image'),
    path('notification/seen/<str:pk>',
         views.notificationSeen, name='seen-notification'),

    path('chat-room/<str:room>/', views.chatRoom, name="chatroom"),
    path('user_active/<str:user_id>/',
         views.check_remote_user_active, name='active-user'),
    path('user/profile/<int:room_id>/<str:username>', views.usernameRedirect, name="username"),

]

studyGroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/',include('base.api.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

from .constants import Status


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# Create your models here.
class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(
        User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]


class Media(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    media_name = models.CharField(max_length=255, null=True)
    media_type = models.CharField(max_length=100, null=True)
    media_size = models.IntegerField(null=True)
    media_path = models.FileField(upload_to='files/', null=True)

    def __str__(self):
        return self.media_name


class Notification(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='sent_notifications')
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='received_notifications')
    type = models.CharField(max_length=100, null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)


class VideoStatus(models.Model):
    room = models.OneToOneField(Room, on_delete=models.CASCADE)
    host = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=50, default=Status.INACTIVE)
    ended = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status


class BaseRoomParticipants(models.Model):
    id = models.AutoField(primary_key=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='room_participant')
    
class UserPreference(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Assuming you have a User model
    selected_topics = models.ManyToManyField('Topic')   

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room, User

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar','name','username','email', 'bio']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.core.exceptions import ObjectDoesNotExist
from rest_framework.exceptions import ValidationError
from django.http import JsonResponse
from base.models import Room, User
from .serializers import RoomSerializer , UsernameSerialization
from base.constants import Status
from django.utils import timezone
from django.shortcuts import get_object_or_404

@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)

@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getRoom(request,pk):
    rooms = Room.objects.get(id=pk)
    serializer = RoomSerializer(rooms, many=False)
    return Response(serializer.data)

@api_view(['GET'])
def getParticipants(request,pk):
    try:
        room = Room.objects.get(id=pk)
    except Room.DoesNotExist:
        return Response({'error': 'Room not found.'}, status=404)
    
    query = request.GET.get('query', '')
    
    Participants = room.participants.filter(username__icontains=query)[:5]
    serializer = UsernameSerialization(Participants, many=True)
    return Response(serializer.data)
   

# @api_view(['POST'])
# def roomCallStatusActive(request):
#     print(request.data.get('roomId'))
         
#     room = Room.objects.get(id=request.data.get('roomId'))
#     host = User.objects.get(id=request.data.get('hostId')) 
#     try:
#             video_status = VideoStatus.objects.get(room=room)
#             # VideoStatus object exists, update the fields
#             video_status.host = host
#             video_status.status = Status.ACTIVE
#             video_status.save()
#     except VideoStatus.DoesNotExist:
#     # VideoStatus object does not exist, create a new one
#             video_status = VideoStatus.objects.create(room=room, host=host, status=Status.ACTIVE)
#             # video_status, created = VideoStatus.objects.get_or_create(
#             #     room=room,
#             #     host= host,
#             #     status = Status.ACTIVE
#             # ) 
#             # if not created:
#             #     # VideoStatus object already exists, update the fields
#             #     video_status.host = host
#             #     video_status.status = Status.ACTIVE
#             #     video_status.save() 
#             # VideoStatus.objects.create(
#             #     room = room,
#             #     host = host,
#             #     status = Status.ACTIVE,      
#             # )    
#             # if(room.call_status == Status.INACTIVE):
#             #     room.call_status = Status.ACTIVE
#             # room.save()
#     return Response(status=200) 

# @api_view(['POST'])
# def roomCallStatusActive(request):
#     try:
#         room_id = request.data.get('roomId')
#         host_id = request.data.get('hostId')
#         if not room_id or not host_id:
#             raise ValidationError("roomId and hostId must be provided.")
        
#         room = Room.objects.get(id=room_id)
#         host = User.objects.get(id=host_id)
        
#         try:
#             video_status = VideoStatus.objects.get(room=room)
#             # VideoStatus object exists, update the fields
#             video_status.host = host.name
#             video_status.status = Status.ACTIVE
#             video_status.save()
#         except ObjectDoesNotExist:
#             video_status = VideoStatus.objects.create(room=room, host=host.name, status=Status.ACTIVE)
        
#         return Response(status=200)
    
#     except (ValidationError, ObjectDoesNotExist) as e:
#         return Response({'error': str(e)}, status=400)
    
#     except Exception as e:
#         # Handle any other exceptions or errors that may occur
#         # Log the error or return an appropriate response
#         print(f"Error occurred: {str(e)}")
#         return Response({'error': 'Internal Server Error'}, status=500)

# @api_view(['POST'])
# def roomCallStatusInactive(request):
#     try:
       
#         room_id = request.data.get('roomId')
#         host_id = request.data.get('hostId')
       
#         if not room_id or not host_id:
#             raise ValidationError("roomId and hostId must be provided.")
        
#         room = Room.objects.get(id=room_id)
#         host = User.objects.get(id=host_id)
        
#         try:
#             video_status = VideoStatus.objects.get(room=room)
#             # VideoStatus object exists, update the fields
#             if video_status.host == host.name:
#               video_status.host = host.name
#               video_status.status = Status.INACTIVE
#               video_status.ended = timezone.now()
#               video_status.save()
#             else:
#                 raise ValidationError("Only can change status.")
                  
#         except ObjectDoesNotExist:
#             return Response(status=404)
        
#         return Response(status=200)
    
#     except (ValidationError, ObjectDoesNotExist) as e:
#         return Response({'error': str(e)}, status=400)
    
#     except Exception as e:
#         # Handle any other exceptions or errors that may occur
#         # Log the error or return an appropriate response
#         print(f"Error occurred: {str(e)}")
#         return Response({'error': 'Internal Server Error'}, status=500)

# @api_view(['GET'])
# def getVideoStatus(request,pk):
#     try: 
#         room = get_object_or_404(Room, id=pk)
#         video = VideoStatus.objects.get(room=room)
#         if video is None:
#            return Response(status=404) 
#         serializer = VideoStatusSerializer(video, many=False)
#         return JsonResponse(serializer.data)
#     except VideoStatus.DoesNotExist:
#         return Response(status=404)

base/templates/base/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{message.user.avatar.url}}" />
          </div>
          <p>
            @{{message.user.username}}
            <span>{{ message.created|timesince }} ago</span>
          </p>
        </a>
        {% if request.user == message.user %}
        <div class="roomListRoom__actions">
          <a href="{% url 'delete-message' message.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
        <div class="activities__boxRoomContent">
            {{message}}
        </div>
      </div>
    </div>

    {% endfor %}
  </div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    {% endblock %}

base/templates/base/feed_component.html
{% for room in rooms%}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{room.host.avatar.url}}" />
        </div>
        <span>@{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created|timesince}} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'room' room.id %}">{{room.name}}</a>
     
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'room' room.id%}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{room.participants.all.count}} Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
  </div>

  {% endfor %}

base/templates/base/home.html
  {% extends 'main.html' %}

  {% block content %}
  <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->

        {% include 'base/topics_component.html'%}
      
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" action="{% url 'home' %}" method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'activities' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{room_count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>

          {% include 'base/feed_component.html'%}

          <div class="pagination">
            {% if rooms.has_previous %}
            <a href="/home/?page=1">First</a>
            <a href="/home/?page={{rooms.previous_page_number}}">&laquo;</a>
            {% endif %}
            {% for i in rooms.paginator.page_range %}
              {% if rooms.number == i %}
                  <a class="active" href="#" >{{ i }}</a>
              {% else %}
                  <a href="/home/?page={{ i }}">{{ i }}</a>
              {% endif %}
           {% endfor %}
           
            {% if rooms.has_next %}
           
            <a href="/home/?page={{rooms.next_page_number}}">&raquo;</a>
            <a href="/home/?page={{rooms.paginator.num_pages}}">Last</a>
            {% endif %}
          </div>
        
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        {% include 'base/activity_component.html'%}
        
        <!-- Activities End -->
      </div>
    </main>
   
{% endblock %}

base/templates/base/hosted_room_list.html
{% for room in hosted_rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room' room.id%}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                ></path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                ></path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                ></path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                ></path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

base/templates/base/reset_password.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
  <div class="layout__box">
    <div class="layout__boxHeader">
      <div class="layout__boxTitle">
        <h3>Forgot Password</h3>
      </div>
    </div>
    <div class="layout__body">
  <h2 class="auth__tagline">Enter your Email</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br/>
    <button type="submit" class="btn btn--main">Continue</button>
  </form>
    </div>
  </div>
</div>
{% endblock %}

base/templates/base/reset_password_done.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
  <div class="layout__box">
    <div class="layout__boxHeader">
      <div class="layout__boxTitle">
        <h3>Success</h3>
      </div>
    </div>
    <div class="layout__body">
  <h2>Password Reset Email Sent</h2>
  <p>We have emailed you instructions on how to reset your password. Please check your email.</p>
    </div>
  </div>
</div>
{% endblock %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search" action="" method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for topics" />
              </label>
            </form>

            <ul class="mod_topics__list">
              <li>
                <a href="{% url 'home' %}" class="active">All <span>{{topics.count}}</span></a>
              </li>
              {% for topic in topics%}
              <li>
                <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
              </li>
             {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/topics_component.html
<div class="topics">
    <div class="roomList__header">
      <p style="font-weight: 900;">Browse Topics</p>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home' %}">All <span>{{topics.count}}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{% url 'home' %}?q={{topic.name}}"> {{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
      </li>
      {% endfor %}
    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
      More
      <span>
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="12" viewBox="0 0 32 32">
          <title>chevron-down</title>
          <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
      </span>
      </a>
  </div>